#!/usr/bin/env python3
"""
piskel_to_h.py — Convert a Piskel PNG sprite sheet to an Arduino header.

Piskel export:  Sprite → Export → PNG → Sprite sheet
                (all frames in one row, width = frame_w × frame_count, height = frame_h)

Usage:
    python tools/piskel_to_h.py <spritesheet.png> [frame_delay_ms]

Output:
    tracker_golf_m4/anim_boot.h   (overwritten in place)

The Golf panel has G and B output channels physically swapped, so every pixel is
encoded as R5B6G5 instead of standard R5G6B5.  The conversion handles this.

Transparent pixels (alpha == 0) are mapped to black (0x0000).
"""

import sys
import os
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: pip install Pillow")

FRAME_W = 64
FRAME_H = 32
OUT_PATH = Path(__file__).parent.parent / "tracker_golf_m4" / "anim_boot.h"


def to_565_swapped(r, g, b):
    # Standard RGB565 is R5G6B5.
    # Golf panel has G and B wires swapped, so we encode as R5B6G5.
    return ((r & 0xF8) << 8) | ((b & 0xFC) << 3) | (g >> 3)


def main():
    if len(sys.argv) < 2:
        sys.exit(f"Usage: python {sys.argv[0]} <spritesheet.png> [frame_delay_ms]")

    src = Path(sys.argv[1])
    if not src.exists():
        sys.exit(f"File not found: {src}")

    delay_ms = int(sys.argv[2]) if len(sys.argv) >= 3 else 80

    img = Image.open(src).convert("RGBA")
    w, h = img.size

    if w % FRAME_W != 0:
        sys.exit(f"Image width ({w}px) is not a multiple of {FRAME_W}. Check your Piskel sprite size.")
    if h % FRAME_H != 0:
        sys.exit(f"Image height ({h}px) is not a multiple of {FRAME_H}. Check your Piskel sprite size.")

    cols = w // FRAME_W
    rows = h // FRAME_H
    n_frames = cols * rows
    pixels = img.load()

    lines = [
        "// anim_boot.h — generated by tools/piskel_to_h.py",
        f"// Source: {src.name}   Frames: {n_frames}   Delay: {delay_ms} ms",
        "// Do not edit by hand — re-run the script to regenerate.",
        "",
        f"#define ANIM_FRAMES   {n_frames}",
        f"#define ANIM_DELAY_MS {delay_ms}",
        "",
        f"const uint16_t PROGMEM bootAnim[{n_frames}][{FRAME_W * FRAME_H}] = {{",
    ]

    for f in range(n_frames):
        col = f % cols
        row = f // cols
        ox = col * FRAME_W
        oy = row * FRAME_H
        row_vals = []
        for y in range(FRAME_H):
            for x in range(FRAME_W):
                r, g, b, a = pixels[ox + x, oy + y]
                c = 0 if a == 0 else to_565_swapped(r, g, b)
                row_vals.append(f"0x{c:04X}")

        # Wrap every 16 values for readability
        chunks = [", ".join(row_vals[i:i+16]) for i in range(0, len(row_vals), 16)]
        inner = ",\n    ".join(chunks)
        comma = "," if f < n_frames - 1 else ""
        lines.append(f"  {{ // frame {f}")
        lines.append(f"    {inner}")
        lines.append(f"  }}{comma}")

    lines += ["};", ""]

    OUT_PATH.write_text("\n".join(lines))
    print(f"Wrote {n_frames} frames ({FRAME_W}×{FRAME_H}) to {OUT_PATH}")
    print(f"Frame delay: {delay_ms} ms  |  Total size: ~{n_frames * FRAME_W * FRAME_H * 2 // 1024} KB in PROGMEM")


if __name__ == "__main__":
    main()
