#!/usr/bin/env python3
"""
piskel_c_to_h.py — Convert a Piskel C array export to an Arduino PROGMEM header.

Piskel export: Sprite → Export → C  (produces a .c file with uint32_t ARGB data)

Usage:
    python tools/piskel_c_to_h.py <piskel_export.c> [frame_delay_ms]

Output:
    tracker_golf/anim_boot.h  (overwritten in place)

Piskel stores each pixel as 0xAARRGGBB.
The Golf panel has G and B output channels physically swapped, so pixels are
encoded as R5B6G5 (not standard R5G6B5). Transparent pixels (alpha=0) → black.
"""

import re
import sys
from pathlib import Path

OUT_PATH = Path(__file__).parent.parent / "tracker_golf" / "anim_boot.h"


def argb_to_565_swapped(val):
    a = (val >> 24) & 0xFF
    if a == 0:
        return 0
    r = (val >> 16) & 0xFF
    g = (val >>  8) & 0xFF
    b =  val        & 0xFF
    # Panel wires G and B swapped → encode as R5B6G5
    return ((r & 0xF8) << 8) | ((b & 0xFC) << 3) | (g >> 3)


def main():
    if len(sys.argv) < 2:
        sys.exit(f"Usage: python {sys.argv[0]} <piskel_export.c> [frame_delay_ms]")

    src = Path(sys.argv[1])
    if not src.exists():
        sys.exit(f"File not found: {src}")

    delay_ms = int(sys.argv[2]) if len(sys.argv) >= 3 else 80

    text = src.read_text()

    # Pull frame count, width, height from #defines
    frame_count = int(re.search(r'#define\s+\w+FRAME_COUNT\s+(\d+)', text).group(1))
    frame_w     = int(re.search(r'#define\s+\w+FRAME_WIDTH\s+(\d+)',  text).group(1))
    frame_h     = int(re.search(r'#define\s+\w+FRAME_HEIGHT\s+(\d+)', text).group(1))
    pixels_per_frame = frame_w * frame_h

    # Extract all hex pixel values in order
    all_vals = [int(h, 16) for h in re.findall(r'0x[0-9a-fA-F]{8}', text)]
    expected = frame_count * pixels_per_frame
    if len(all_vals) != expected:
        sys.exit(f"Expected {expected} pixels ({frame_count}×{pixels_per_frame}), got {len(all_vals)}")

    lines = [
        f"// anim_boot.h — generated by tools/piskel_c_to_h.py",
        f"// Source: {src.name}   Frames: {frame_count}   Delay: {delay_ms} ms   Size: {frame_w}×{frame_h}",
        f"// Do not edit by hand — re-run the script to regenerate.",
        f"",
        f"#define ANIM_FRAMES   {frame_count}",
        f"#define ANIM_DELAY_MS {delay_ms}",
        f"",
        f"const uint16_t PROGMEM bootAnim[{frame_count}][{pixels_per_frame}] = {{",
    ]

    for f in range(frame_count):
        chunk = all_vals[f * pixels_per_frame : (f + 1) * pixels_per_frame]
        converted = [f"0x{argb_to_565_swapped(v):04X}" for v in chunk]
        rows = [", ".join(converted[i:i+16]) for i in range(0, len(converted), 16)]
        comma = "," if f < frame_count - 1 else ""
        lines.append(f"  {{ // frame {f}")
        lines.append("    " + ",\n    ".join(rows))
        lines.append(f"  }}{comma}")

    lines += ["};", ""]

    OUT_PATH.write_text("\n".join(lines))
    size_kb = frame_count * pixels_per_frame * 2 // 1024
    print(f"Wrote {frame_count} frames ({frame_w}×{frame_h}) → {OUT_PATH}")
    print(f"Frame delay: {delay_ms} ms  |  PROGMEM size: ~{size_kb} KB")


if __name__ == "__main__":
    main()
